micronaut:
  application:
    name: apiConfrontosTorneioFutebol
datasources:
  default:
    url: jdbc:mysql://localhost:3306/torneio_futebol_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: nanuko135
    db-type: mysql
    schema-generate: UPDATE
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true