micronaut.server.port: 8081
micronaut:
  application:
    name: apiConfrontosTorneioFutebol
datasources:
  default:
    url: jdbc:mysql://localhost:3306/torneio_futebol_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: nanuko135
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
kafka.bootstrap.servers: localhost:9092
api.criacao.topico: 'CAMPEONATO.EQUIPES'
api.confronto.topico: 'CAMPEONATO.ACRESCIMO.CONFRONTO'